version: "3.9"

services:
  gateway:
    image: quay.io/arktos-venture/ibkr-gateway:latest
    volumes:
      - ./gateway/config/config.ini:/opt/ibc/config.ini
      - ./gateway/config/proxy.yaml:/home/trader/proxy.yaml
    environment:
      - TCP_TUNNEL_ENABLED=true
    restart: unless-stopped
    stop_signal: SIGKILL
    ports:
      - 3000:3000
      - 5000:5000
