version: "3.9"

services:
  gateway:
    image: quay.io/arktos-venture/ibkr-gateway:latest
    volumes:
      - ./gateway/config/config.ini:/opt/ibc/config.ini
      - ./gateway/config/proxy.yaml:/home/trader/proxy.yaml
    restart: unless-stopped
    stop_signal: SIGKILL
    ports:
      - 6080:6080
      - 5001:5000
