version: "3.9"

services:
  gateway:
    image: quay.io/hartza-capital/ib-gateway:stable
    volumes:
      - ./gateway/config.ini:/opt/ibc/config.ini
      - ./gateway/scripts/gatewaystart.sh:/opt/ibc/scripts/gatewaystart.sh
    environment:
      - VNC_SERVER_PASSWORD=test
    restart: unless-stopped
    stop_signal: SIGKILL
    ports:
      - 5900:5900
      - 4001:4001
