services:
  tws:
    build:
      context: ./app/tws
      dockerfile: Dockerfile
      args:
        IBC_VERSION: 3.12.0
    ports:
      - "6080:6080"
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - config.ini:/opt/ibc/config.ini
    stop_signal: SIGKILL
    environment:
      TWS_MAJOR_VRSN: 1012

  gateway:
    build:
      context: ./app/gateway
      dockerfile: Dockerfile.gateway
      args:
        IBC_VERSION: 3.12.0
    image: gateway:latest
    ports:
      - "6081:6080"
      - "8889:8888"
    restart: unless-stopped
    volumes:
      - ./app/config.ini:/opt/ibc/config.ini
    stop_signal: SIGKILL
    environment:
      TWS_MAJOR_VRSN: 1012
